# config/default.yaml
defaults:
  - trainer: base
  - model: student
  - _self_

mode: sequential  # [teacher|student|sequential]
teacher_epochs: 10
student_epochs: 20
distill_alpha: 0.5
warmup_epochs: 5
